#!/usr/bin/env node
/**
 * Playground Test Script for: filemaker-removal-requirements
 * Auto-generated by devFlow
 *
 * Usage: node playground.js <scenario-slug>
 * Example: node playground.js forgot-password
 */

const fs = require('fs');
const path = require('path');
const { execSync, spawn } = require('child_process');

// NOTE: This is a Node.js CommonJS script testing an ES Module project
// We cannot directly import ES modules, so we use dynamic import() or spawn processes
// that load the modules in their native environment

/**
 * Entry Points Mapping (from contracts.md analysis):
 *
 * 1. Environment Detection:
 *    - src/components/auth/SignIn.jsx:detectFileMaker() - checks window.FileMaker
 *    - src/services/dataService.js:setEnvironmentContext() - sets global env state
 *    - src/services/dataService.js:getEnvironmentContext() - retrieves env state
 *
 * 2. Backend API Routing:
 *    - src/api/fileMaker.js:fetchDataFromFileMaker() - routes to backend or FM
 *    - src/api/fileMaker.js:generateBackendAuthHeader() - HMAC auth generation
 *    - src/api/customers.js:fetchCustomers() - customer operations via FileMaker API
 *
 * 3. Authentication:
 *    - src/services/supabaseService.js:signInWithEmail() - Supabase auth
 *    - src/services/dataService.js:AUTH_METHODS - auth method constants
 *
 * 4. File Existence Checks:
 *    - File system operations to verify FileMaker files are removed
 *    - Grep operations to find FileMaker references
 *
 * 5. Build Process:
 *    - npm run build command execution
 *    - Exit code and output validation
 */

// JSONL event logger
class EventLogger {
  constructor(outputPath) {
    this.outputPath = outputPath;
    this.events = [];
  }

  log(type, message, data = {}, success = null) {
    const event = {
      type,
      timestamp: new Date().toISOString(),
      message,
      data,
      ...(success !== null && { success }),
    };
    this.events.push(event);
    console.log(JSON.stringify(event));
    fs.appendFileSync(this.outputPath, JSON.stringify(event) + '\n');
  }

  start() { this.log('start', 'Scenario execution started'); }
  input(name, value) { this.log('input', `Input: ${name}`, { name, value }); }
  output(name, value) { this.log('output', `Output: ${name}`, { name, value }); }
  assertion(name, passed, expected, actual) {
    this.log('assertion', `Assertion: ${name}`, { expected, actual }, passed);
  }
  cleanup(message) { this.log('cleanup', message); }
  end(success, error = null) {
    this.log('end', success ? 'Scenario passed' : 'Scenario failed', { error }, success);
  }
  error(message, err) { this.log('error', message, { error: err?.message || err }); }
}

// Cleanup tracker
const createdRecords = [];
function trackCreated(type, id) {
  createdRecords.push({ type, id });
}

/**
 * Helper: Execute shell command and return output
 */
function execCommand(command, options = {}) {
  try {
    const output = execSync(command, {
      cwd: path.join(__dirname, '../..'),
      encoding: 'utf8',
      stdio: options.silent ? 'pipe' : 'inherit',
      ...options
    });
    return { success: true, output, exitCode: 0 };
  } catch (error) {
    return {
      success: false,
      output: error.stdout || error.stderr || error.message,
      exitCode: error.status || 1,
      error
    };
  }
}

/**
 * Helper: Check if file exists
 */
function fileExists(filePath) {
  const fullPath = path.join(__dirname, '../..', filePath);
  return fs.existsSync(fullPath);
}

/**
 * Helper: Grep for pattern in codebase
 */
function grepCodebase(pattern, options = {}) {
  const baseDir = path.join(__dirname, '../..');
  const searchPath = options.path || 'src';
  const cmd = `grep -r "${pattern}" ${searchPath} || true`;

  try {
    const output = execSync(cmd, {
      cwd: baseDir,
      encoding: 'utf8',
      stdio: 'pipe'
    });

    const matches = output.trim().split('\n').filter(line => line.length > 0);
    return {
      found: matches.length > 0,
      matches,
      count: matches.length
    };
  } catch (error) {
    return {
      found: false,
      matches: [],
      count: 0,
      error: error.message
    };
  }
}

/**
 * Helper: Check environment variables
 */
function checkEnvVars() {
  const baseDir = path.join(__dirname, '../..');
  const envPath = path.join(baseDir, '.env');

  if (!fs.existsSync(envPath)) {
    return { exists: false, vars: {} };
  }

  const envContent = fs.readFileSync(envPath, 'utf8');
  const vars = {};

  envContent.split('\n').forEach(line => {
    const match = line.match(/^([^=]+)=(.*)$/);
    if (match) {
      vars[match[1].trim()] = !!match[2].trim();
    }
  });

  return { exists: true, vars };
}

/**
 * Preflight: Ensure all requirements are ready before running scenarios
 */
async function ensureRequirements(logger) {
  logger.log('info', 'Checking requirements...');

  const checks = {
    projectRoot: false,
    packageJson: false,
    srcDirectory: false,
    envFile: false,
    nodeModules: false,
    buildScript: false
  };

  try {
    // Check project root structure
    const baseDir = path.join(__dirname, '../..');
    checks.projectRoot = fs.existsSync(baseDir);

    // Check package.json
    const packageJsonPath = path.join(baseDir, 'package.json');
    checks.packageJson = fs.existsSync(packageJsonPath);

    // Check src directory
    const srcDir = path.join(baseDir, 'src');
    checks.srcDirectory = fs.existsSync(srcDir);

    // Check .env file
    const envPath = path.join(baseDir, '.env');
    checks.envFile = fs.existsSync(envPath);

    // Check node_modules
    const nodeModulesPath = path.join(baseDir, 'node_modules');
    checks.nodeModules = fs.existsSync(nodeModulesPath);

    // Check if build script exists
    if (checks.packageJson) {
      const packageJson = JSON.parse(fs.readFileSync(packageJsonPath, 'utf8'));
      checks.buildScript = !!packageJson.scripts?.build;
    }

    logger.output('requirements_check', checks);

    // All critical checks must pass
    const allPassed = checks.projectRoot && checks.packageJson && checks.srcDirectory;

    if (!allPassed) {
      logger.error('Requirements check failed', checks);
      return false;
    }

    logger.log('info', 'All requirements satisfied');
    return true;

  } catch (error) {
    logger.error('Requirements check error', error);
    return false;
  }
}

async function cleanup(logger) {
  for (const record of createdRecords.reverse()) {
    try {
      // Cleanup based on record type
      switch (record.type) {
        case 'test-file':
          const filePath = path.join(__dirname, '../..', record.id);
          if (fs.existsSync(filePath)) {
            fs.unlinkSync(filePath);
            logger.cleanup(`Deleted test file: ${record.id}`);
          }
          break;
        case 'test-dir':
          const dirPath = path.join(__dirname, '../..', record.id);
          if (fs.existsSync(dirPath)) {
            fs.rmSync(dirPath, { recursive: true });
            logger.cleanup(`Deleted test directory: ${record.id}`);
          }
          break;
        default:
          logger.cleanup(`Cleaned up ${record.type}: ${record.id}`);
      }
    } catch (err) {
      logger.error(`Failed to cleanup ${record.type}: ${record.id}`, err);
    }
  }
}

/**
 * Scenario Runners
 * Each scenario maps to a specific test implementation
 */

const scenarioRunners = {
  /**
   * Scenario: Environment detection without FileMaker
   * Verify app correctly detects web app environment when FileMaker objects are absent
   */
  'environment-detection-without-filemaker': async (inputs, logger) => {
    // Check that dataService.js has environment detection logic
    const dataServiceExists = fileExists('src/services/dataService.js');
    logger.output('dataService_exists', dataServiceExists);

    if (!dataServiceExists) {
      throw new Error('dataService.js not found');
    }

    // Check for ENVIRONMENT_TYPES constants
    const envTypesCheck = grepCodebase('ENVIRONMENT_TYPES', { path: 'src/services/dataService.js' });
    logger.output('environment_types_found', envTypesCheck);

    // Check for AUTH_METHODS constants
    const authMethodsCheck = grepCodebase('AUTH_METHODS', { path: 'src/services/dataService.js' });
    logger.output('auth_methods_found', authMethodsCheck);

    // Check SignIn component has detection logic
    const signInExists = fileExists('src/components/auth/SignIn.jsx');
    logger.output('signin_component_exists', signInExists);

    if (signInExists) {
      const fmDetectCheck = grepCodebase('detectFileMaker', { path: 'src/components/auth/SignIn.jsx' });
      logger.output('detectFileMaker_function_found', fmDetectCheck);
    }

    // Check for FileMaker references in environment detection paths (for the assertion)
    const fileMakerRefsCheck = grepCodebase('FileMaker', {
      path: 'src/components/auth/SignIn.jsx src/services/dataService.js'
    });
    logger.output('filemaker_references_check', fileMakerRefsCheck);

    const resultObject = {
      dataServiceExists,
      hasEnvironmentTypes: envTypesCheck.found,
      hasAuthMethods: authMethodsCheck.found,
      signInExists,
      hasDetectFileMaker: signInExists && grepCodebase('detectFileMaker', { path: 'src/components/auth/SignIn.jsx' }).found,
    };

    // Add the FileMaker integration removal status - return count (0 = no matches = success)
    // Note: Using count instead of boolean to avoid falsy value fallback issue in line 976
    resultObject['FileMaker integration removal status'] = fileMakerRefsCheck.count;

    return resultObject;
  },

  /**
   * Scenario: Backend API routing for customer operations
   * Verify customer CRUD operations route through backend API instead of FileMaker
   */
  'backend-api-routing-for-customer-operations': async (inputs, logger) => {
    // Check customers API file exists
    const customersApiExists = fileExists('src/api/customers.js');
    logger.output('customers_api_exists', customersApiExists);

    if (!customersApiExists) {
      throw new Error('customers.js API file not found');
    }

    // Check for fetchDataFromFileMaker calls
    const fetchCallsCheck = grepCodebase('fetchDataFromFileMaker', { path: 'src/api/customers.js' });
    logger.output('fetchDataFromFileMaker_calls', fetchCallsCheck);

    // Check for HMAC auth generation
    const hmacCheck = grepCodebase('generateBackendAuthHeader', { path: 'src' });
    logger.output('hmac_auth_found', hmacCheck);

    // Check backend config exists
    const configExists = fileExists('src/config.js');
    logger.output('config_exists', configExists);

    if (configExists) {
      const backendConfigCheck = grepCodebase('backendConfig', { path: 'src/config.js' });
      logger.output('backend_config_defined', backendConfigCheck);
    }

    return {
      customersApiExists,
      usesFetchDataFromFileMaker: fetchCallsCheck.found,
      hasHmacAuth: hmacCheck.found,
      configExists,
      hasBackendConfig: configExists && grepCodebase('backendConfig', { path: 'src/config.js' }).found
    };
  },

  /**
   * Scenario: Supabase-only authentication flow
   * Verify authentication uses only Supabase without FileMaker auto-detection
   */
  'supabase-only-authentication-flow': async (inputs, logger) => {
    // Check Supabase service exists
    const supabaseServiceExists = fileExists('src/services/supabaseService.js');
    logger.output('supabase_service_exists', supabaseServiceExists);

    if (!supabaseServiceExists) {
      throw new Error('supabaseService.js not found');
    }

    // Check for signInWithEmail function
    const signInCheck = grepCodebase('signInWithEmail', { path: 'src/services/supabaseService.js' });
    logger.output('signInWithEmail_found', signInCheck);

    // Check SignIn component for FileMaker detection delay
    const signInComponentExists = fileExists('src/components/auth/SignIn.jsx');
    if (signInComponentExists) {
      const detectionDelayCheck = grepCodebase('3 seconds', { path: 'src/components/auth/SignIn.jsx' });
      logger.output('has_detection_delay', detectionDelayCheck);
    }

    // Check for Supabase client creation
    const supabaseClientCheck = grepCodebase('createClient', { path: 'src/services/supabaseService.js' });
    logger.output('supabase_client_created', supabaseClientCheck);

    return {
      supabaseServiceExists,
      hasSignInWithEmail: signInCheck.found,
      hasDetectionDelay: signInComponentExists && grepCodebase('3 seconds', { path: 'src/components/auth/SignIn.jsx' }).found,
      hasSupabaseClient: supabaseClientCheck.found
    };
  },

  /**
   * Scenario: Remove FileMaker bridge files
   * Verify all FileMaker bridge files are removed from codebase
   */
  'remove-filemaker-bridge-files': async (inputs, logger) => {
    // Check if FileMaker bridge files still exist
    const fileMakerApiExists = fileExists('src/api/fileMaker.js');
    logger.output('fileMaker_api_exists', fileMakerApiExists);

    // Check for useFileMakerBridge hook references
    const bridgeHookCheck = grepCodebase('useFileMakerBridge', { path: 'src' });
    logger.output('useFileMakerBridge_references', bridgeHookCheck);

    // Check for FMGofer references
    const fmGoferCheck = grepCodebase('FMGofer', { path: 'src' });
    logger.output('FMGofer_references', fmGoferCheck);

    // Check for fetchDataFromFileMaker references
    const fetchDataCheck = grepCodebase('fetchDataFromFileMaker', { path: 'src' });
    logger.output('fetchDataFromFileMaker_references', fetchDataCheck);

    return {
      fileMakerApiStillExists: fileMakerApiExists,
      hasBridgeHookReferences: bridgeHookCheck.found,
      hasFMGoferReferences: fmGoferCheck.found,
      hasFetchDataReferences: fetchDataCheck.found
    };
  },

  /**
   * Scenario: Remove environment detection logic
   * Verify environment detection and routing logic is simplified to single path
   */
  'remove-environment-detection-logic': async (inputs, logger) => {
    // Check for ENVIRONMENT_TYPES.FILEMAKER constant
    const fileMakerEnvCheck = grepCodebase('ENVIRONMENT_TYPES.FILEMAKER', { path: 'src' });
    logger.output('ENVIRONMENT_TYPES_FILEMAKER_found', fileMakerEnvCheck);

    // Check for useFileMaker flag in axios interceptors
    const useFileMakerCheck = grepCodebase('useFileMaker', { path: 'src' });
    logger.output('useFileMaker_flag_found', useFileMakerCheck);

    // Check dataService for dual routing
    const dataServiceExists = fileExists('src/services/dataService.js');
    if (dataServiceExists) {
      const dualRoutingCheck = grepCodebase('convertToFileMakerCall', { path: 'src/services/dataService.js' });
      logger.output('dual_routing_logic_found', dualRoutingCheck);
    }

    // Check initialization service for FileMaker detection
    const initServiceExists = fileExists('src/services/initializationService.js');
    if (initServiceExists) {
      const fmDetectionCheck = grepCodebase('FileMaker', { path: 'src/services/initializationService.js' });
      logger.output('initialization_fm_detection_found', fmDetectionCheck);
    }

    return {
      hasFileMakerEnvType: fileMakerEnvCheck.found,
      hasUseFileMakerFlag: useFileMakerCheck.found,
      hasDualRouting: dataServiceExists && grepCodebase('convertToFileMakerCall', { path: 'src/services/dataService.js' }).found,
      hasInitFMDetection: initServiceExists && grepCodebase('FileMaker', { path: 'src/services/initializationService.js' }).found
    };
  },

  /**
   * Scenario: Backend API compatibility
   * Verify backend API supports all operations previously done via FileMaker
   */
  'backend-api-compatibility': async (inputs, logger) => {
    // Check config for backend API endpoints
    const configExists = fileExists('src/config.js');
    if (!configExists) {
      throw new Error('config.js not found');
    }

    const backendConfigCheck = grepCodebase('backendConfig', { path: 'src/config.js' });
    logger.output('backend_config_exists', backendConfigCheck);

    // Check for API files that should use backend
    const apiFiles = [
      'customers.js',
      'projects.js',
      'tasks.js',
      'teams.js',
      'notes.js',
      'links.js',
      'financialRecords.js'
    ];

    const apiFilesStatus = {};
    for (const apiFile of apiFiles) {
      apiFilesStatus[apiFile] = fileExists(`src/api/${apiFile}`);
    }

    logger.output('api_files_status', apiFilesStatus);

    // Check for HMAC authentication implementation
    const hmacCheck = grepCodebase('generateBackendAuthHeader', { path: 'src' });
    logger.output('hmac_implementation', hmacCheck);

    return {
      hasBackendConfig: backendConfigCheck.found,
      apiFiles: apiFilesStatus,
      allApiFilesExist: Object.values(apiFilesStatus).every(exists => exists),
      hasHmacAuth: hmacCheck.found
    };
  },

  /**
   * Scenario: Project builds without FileMaker dependencies
   * Verify project builds successfully after removing FileMaker code
   */
  'project-builds-without-filemaker-dependencies': async (inputs, logger) => {
    logger.log('info', 'Running build process...');

    // Execute npm run build
    const buildResult = execCommand('npm run build', { silent: false });

    logger.output('build_result', {
      success: buildResult.success,
      exitCode: buildResult.exitCode
    });

    if (!buildResult.success) {
      logger.error('Build failed', buildResult.output);

      // Check for FileMaker-related errors
      const output = buildResult.output || '';
      const hasFMErrors = output.includes('FileMaker') || output.includes('FMGofer') || output.includes('fm-gofer');

      logger.output('has_filemaker_errors', hasFMErrors);

      return {
        buildSucceeded: false,
        hasFileMakerErrors: hasFMErrors,
        errorOutput: output.substring(0, 500) // Limit error output
      };
    }

    // Check that dist directory was created
    const distExists = fileExists('dist');
    logger.output('dist_directory_created', distExists);

    return {
      buildSucceeded: true,
      distCreated: distExists,
      hasFileMakerErrors: false
    };
  },

  /**
   * Scenario: Acceptance criteria verification script
   * Run automated verification script to check all acceptance criteria
   */
  'acceptance-criteria-verification-script': async (inputs, logger) => {
    // Check if verification script exists
    const scriptExists = fileExists('scripts/verify-filemaker-removal.sh');
    logger.output('verification_script_exists', scriptExists);

    if (!scriptExists) {
      logger.log('warning', 'Verification script not found, running manual checks');

      // Run manual checks instead
      const checks = [];

      // Check 1: No FileMaker references
      const fmCheck = grepCodebase('FileMaker', { path: 'src' });
      checks.push({ name: 'No FileMaker references', passed: !fmCheck.found });

      // Check 2: No FMGofer references
      const goferCheck = grepCodebase('FMGofer', { path: 'src' });
      checks.push({ name: 'No FMGofer references', passed: !goferCheck.found });

      // Check 3: No fetchDataFromFileMaker
      const fetchCheck = grepCodebase('fetchDataFromFileMaker', { path: 'src' });
      checks.push({ name: 'No fetchDataFromFileMaker', passed: !fetchCheck.found });

      // Check 4: No ENVIRONMENT_TYPES.FILEMAKER
      const envCheck = grepCodebase('ENVIRONMENT_TYPES.FILEMAKER', { path: 'src' });
      checks.push({ name: 'No ENVIRONMENT_TYPES.FILEMAKER', passed: !envCheck.found });

      logger.output('manual_verification_checks', checks);

      const passedCount = checks.filter(c => c.passed).length;
      const totalCount = checks.length;

      return {
        scriptExists: false,
        manualChecksPassed: passedCount,
        manualChecksTotal: totalCount,
        allChecksPassed: passedCount === totalCount,
        checks
      };
    }

    // If script exists, run it
    const scriptResult = execCommand('bash scripts/verify-filemaker-removal.sh', { silent: false });

    logger.output('script_result', {
      success: scriptResult.success,
      exitCode: scriptResult.exitCode
    });

    return {
      scriptExists: true,
      scriptPassed: scriptResult.success,
      output: scriptResult.output?.substring(0, 1000)
    };
  },

  /**
   * Scenario: HMAC authentication for all backend requests
   * Verify all backend API requests include valid HMAC authorization
   */
  'hmac-authentication-for-all-backend-requests': async (inputs, logger) => {
    // Check for generateBackendAuthHeader implementation
    const hmacImplementations = grepCodebase('generateBackendAuthHeader', { path: 'src' });
    logger.output('hmac_implementations', hmacImplementations);

    // Check dataService for HMAC usage
    const dataServiceExists = fileExists('src/services/dataService.js');
    if (dataServiceExists) {
      const dataServiceHmac = grepCodebase('generateBackendAuthHeader', { path: 'src/services/dataService.js' });
      logger.output('dataService_uses_hmac', dataServiceHmac);
    }

    // Check fileMaker API for HMAC usage
    const fileMakerApiExists = fileExists('src/api/fileMaker.js');
    if (fileMakerApiExists) {
      const fileMakerHmac = grepCodebase('generateBackendAuthHeader', { path: 'src/api/fileMaker.js' });
      logger.output('fileMaker_api_uses_hmac', fileMakerHmac);
    }

    // Check for Bearer token format
    const bearerTokenCheck = grepCodebase('Bearer.*timestamp', { path: 'src' });
    logger.output('bearer_token_format', bearerTokenCheck);

    // Check for crypto.subtle usage (Web Crypto API)
    const cryptoCheck = grepCodebase('crypto.subtle', { path: 'src' });
    logger.output('uses_web_crypto_api', cryptoCheck);

    return {
      hasHmacImplementation: hmacImplementations.found,
      hmacCount: hmacImplementations.count,
      dataServiceUsesHmac: dataServiceExists && grepCodebase('generateBackendAuthHeader', { path: 'src/services/dataService.js' }).found,
      fileMakerApiUsesHmac: fileMakerApiExists && grepCodebase('generateBackendAuthHeader', { path: 'src/api/fileMaker.js' }).found,
      usesCryptoApi: cryptoCheck.found
    };
  },

  /**
   * Scenario: Remove FileMaker config and constants
   * Verify FileMaker configuration and constants are removed
   */
  'remove-filemaker-config-and-constants': async (inputs, logger) => {
    // Check config.js for FileMaker config
    const configExists = fileExists('src/config.js');
    if (!configExists) {
      throw new Error('config.js not found');
    }

    const fileMakerConfigCheck = grepCodebase('fileMakerConfig', { path: 'src/config.js' });
    logger.output('fileMaker_config_found', fileMakerConfigCheck);

    // Check for VITE_FM_* environment variables
    const envVars = checkEnvVars();
    logger.output('env_vars_check', envVars);

    const fmEnvVars = Object.keys(envVars.vars).filter(key => key.startsWith('VITE_FM_'));
    logger.output('filemaker_env_vars', fmEnvVars);

    // Check for FM_LAYOUTS constants
    const layoutsCheck = grepCodebase('FM_LAYOUTS', { path: 'src' });
    logger.output('FM_LAYOUTS_found', layoutsCheck);

    // Check for FM_ACTIONS constants
    const actionsCheck = grepCodebase('FM_ACTIONS', { path: 'src' });
    logger.output('FM_ACTIONS_found', actionsCheck);

    // Check for Layouts constant
    const layoutsConstCheck = grepCodebase('Layouts\\.', { path: 'src' });
    logger.output('Layouts_constant_found', layoutsConstCheck);

    return {
      hasFileMakerConfig: fileMakerConfigCheck.found,
      hasFileMakerEnvVars: fmEnvVars.length > 0,
      fmEnvVarCount: fmEnvVars.length,
      hasLayoutsConstants: layoutsCheck.found,
      hasActionsConstants: actionsCheck.found
    };
  },

  /**
   * Scenario: UI components work without FileMaker context
   * Verify UI components render and function correctly without FileMaker environment
   */
  'ui-components-work-without-filemaker-context': async (inputs, logger) => {
    // Check key UI components exist
    const components = [
      'components/CustomerDetails.jsx',
      'components/ProjectDetails.jsx',
      'components/proposals/ProposalCreationForm.jsx'
    ];

    const componentStatus = {};
    for (const component of components) {
      const exists = fileExists(`src/${component}`);
      componentStatus[component] = exists;

      if (exists) {
        // Check if component has FileMaker dependencies
        const fmCheck = grepCodebase('FileMaker', { path: `src/${component}` });
        componentStatus[`${component}_has_fm_deps`] = fmCheck.found;
      }
    }

    logger.output('component_status', componentStatus);

    // Check for useFileMakerBridge usage in components
    const bridgeUsageCheck = grepCodebase('useFileMakerBridge', { path: 'src/components' });
    logger.output('components_use_fm_bridge', bridgeUsageCheck);

    return {
      components: componentStatus,
      allComponentsExist: Object.entries(componentStatus)
        .filter(([key]) => !key.includes('_has_fm_deps'))
        .every(([_, exists]) => exists),
      componentsHaveFMDeps: Object.entries(componentStatus)
        .filter(([key]) => key.includes('_has_fm_deps'))
        .some(([_, hasDeps]) => hasDeps),
      bridgeUsageInComponents: bridgeUsageCheck.found
    };
  },

  /**
   * Scenario: Rollback procedure validation
   * Verify rollback procedure can restore FileMaker functionality if needed
   */
  'rollback-procedure-validation': async (inputs, logger) => {
    // Check git status
    const gitStatusResult = execCommand('git status --short', { silent: true });
    logger.output('git_status', {
      success: gitStatusResult.success,
      hasChanges: gitStatusResult.output?.trim().length > 0
    });

    // Get current commit SHA
    const gitShaResult = execCommand('git rev-parse HEAD', { silent: true });
    logger.output('current_commit', {
      success: gitShaResult.success,
      sha: gitShaResult.output?.trim().substring(0, 7)
    });

    // Check git log for previous commits
    const gitLogResult = execCommand('git log --oneline -n 5', { silent: true });
    logger.output('recent_commits', {
      success: gitLogResult.success,
      commits: gitLogResult.output?.trim().split('\n').slice(0, 5)
    });

    // Verify package.json has necessary scripts
    const packageJsonPath = path.join(__dirname, '../..', 'package.json');
    const packageJson = JSON.parse(fs.readFileSync(packageJsonPath, 'utf8'));

    const hasNpmInstall = !!packageJson.scripts;
    logger.output('has_npm_scripts', hasNpmInstall);

    return {
      gitAvailable: gitStatusResult.success,
      currentCommitSha: gitShaResult.output?.trim().substring(0, 7),
      canRollback: gitStatusResult.success && gitShaResult.success,
      hasPackageJson: !!packageJson,
      hasNpmScripts: hasNpmInstall
    };
  },

  /**
   * Scenario: Zero FileMaker references in codebase
   * Verify comprehensive removal of all FileMaker references from source code
   */
  'zero-filemaker-references-in-codebase': async (inputs, logger) => {
    const patterns = [
      { name: 'FileMaker', pattern: 'FileMaker' },
      { name: 'FMGofer', pattern: 'FMGofer' },
      { name: 'fetchDataFromFileMaker', pattern: 'fetchDataFromFileMaker' },
      { name: 'ENVIRONMENT_TYPES.FILEMAKER', pattern: 'ENVIRONMENT_TYPES.FILEMAKER' },
      { name: 'fm-gofer', pattern: 'fm-gofer' },
      { name: 'PerformScript', pattern: 'PerformScript' },
      { name: 'useFileMakerBridge', pattern: 'useFileMakerBridge' }
    ];

    const results = {};
    let totalMatches = 0;

    for (const { name, pattern } of patterns) {
      const check = grepCodebase(pattern, { path: 'src' });
      results[name] = {
        found: check.found,
        count: check.count,
        matches: check.matches.slice(0, 5) // Limit to first 5 matches
      };
      totalMatches += check.count;
    }

    logger.output('filemaker_references', results);
    logger.output('total_references_found', totalMatches);

    return {
      patterns: results,
      totalReferences: totalMatches,
      hasZeroReferences: totalMatches === 0
    };
  },

  /**
   * Scenario: Backend change requests implemented
   * Verify all backend change requests (BCR-001 through BCR-005) are implemented
   */
  'backend-change-requests-implemented': async (inputs, logger) => {
    // Check for backend change request documents
    const bcrFiles = [
      'BACKEND_CHANGE_REQUEST_001',
      'BACKEND_CHANGE_REQUEST_002',
      'BACKEND_CHANGE_REQUEST_003',
      'BACKEND_CHANGE_REQUEST_004',
      'BACKEND_CHANGE_REQUEST_005'
    ];

    const bcrStatus = {};
    for (const bcrFile of bcrFiles) {
      // Check both .md and without extension
      const mdExists = fileExists(`${bcrFile}.md`);
      const noExtExists = fileExists(bcrFile);
      bcrStatus[bcrFile] = mdExists || noExtExists;
    }

    logger.output('bcr_documents_status', bcrStatus);

    // Check if backend API requirements document exists
    const backendReqsExists = fileExists('requirements/platform-filemaker-removal/backend-api-requirements.md');
    logger.output('backend_requirements_doc_exists', backendReqsExists);

    // Check config for backend endpoints
    const configExists = fileExists('src/config.js');
    if (configExists) {
      const backendApiCheck = grepCodebase('api.claritybusinesssolutions.ca', { path: 'src/config.js' });
      logger.output('backend_api_configured', backendApiCheck);
    }

    return {
      bcrDocuments: bcrStatus,
      backendRequirementsDocExists: backendReqsExists,
      backendApiConfigured: configExists && grepCodebase('api.claritybusinesssolutions.ca', { path: 'src/config.js' }).found
    };
  },

  /**
   * Scenario: Monitoring and alerting active
   * Verify monitoring captures metrics and alerts fire correctly post-deployment
   */
  'monitoring-and-alerting-active': async (inputs, logger) => {
    // Check for error tracking integration
    const errorTrackingCheck = grepCodebase('Sentry\\|Rollbar\\|error tracking', { path: 'src' });
    logger.output('error_tracking_found', errorTrackingCheck);

    // Check for logging service
    const loggingCheck = grepCodebase('console\\.log\\|console\\.error', { path: 'src' });
    logger.output('logging_found', loggingCheck);

    // Check for monitoring configuration
    const monitoringConfigCheck = grepCodebase('monitoring\\|metrics\\|telemetry', { path: 'src' });
    logger.output('monitoring_config_found', monitoringConfigCheck);

    // Note: Cannot test actual monitoring/alerting without live backend
    logger.log('warning', 'Actual monitoring/alerting requires live backend - checking configuration only');

    return {
      hasErrorTracking: errorTrackingCheck.found,
      hasLogging: loggingCheck.found,
      hasMonitoringConfig: monitoringConfigCheck.found,
      note: 'Live monitoring requires deployed backend'
    };
  }
};

/**
 * Helper: Check assertions
 */
function checkAssertion(expected, actual) {
  const assertion = expected.assertion || '';

  // Handle different assertion types
  if (assertion.includes('should return')) {
    // Check for truthiness or specific value
    if (assertion.includes('zero') || assertion.includes('no matches')) {
      return actual === 0 || actual === false || (Array.isArray(actual) && actual.length === 0);
    }
    return !!actual;
  }

  if (assertion.includes('should contain') || assertion.includes('should include')) {
    if (typeof actual === 'object' && actual !== null) {
      return Object.keys(actual).length > 0;
    }
    return !!actual;
  }

  if (assertion.includes('should generate') || assertion.includes('should create')) {
    return !!actual;
  }

  if (assertion.includes('should route')) {
    return !!actual;
  }

  // Default: check truthiness
  return !!actual;
}

// Main execution
async function main() {
  const scenarioSlug = process.argv[2];
  if (!scenarioSlug) {
    console.error('Usage: node playground.js <scenario-slug>');
    console.error('Available scenarios: environment-detection-without-filemaker, backend-api-routing-for-customer-operations, supabase-only-authentication-flow, remove-filemaker-bridge-files, remove-environment-detection-logic, backend-api-compatibility, project-builds-without-filemaker-dependencies, acceptance-criteria-verification-script, hmac-authentication-for-all-backend-requests, remove-filemaker-config-and-constants, ui-components-work-without-filemaker-context, rollback-procedure-validation, zero-filemaker-references-in-codebase, backend-change-requests-implemented, monitoring-and-alerting-active');
    process.exit(1);
  }

  const resultsDir = path.join(__dirname, 'results', scenarioSlug === '__preflight__' ? '__preflight__' : scenarioSlug);
  fs.mkdirSync(resultsDir, { recursive: true });
  const outputPath = path.join(resultsDir, 'execution.jsonl');

  // Clear previous results
  if (fs.existsSync(outputPath)) {
    fs.unlinkSync(outputPath);
  }

  const logger = new EventLogger(outputPath);

  if (scenarioSlug === '__preflight__') {
    let success = false;
    try {
      logger.start();
      success = await ensureRequirements(logger);
    } catch (err) {
      logger.error('Preflight failed', err);
      success = false;
    } finally {
      logger.end(success, success ? null : 'See error events above');
    }
    process.exit(success ? 0 : 1);
  }

  const eventFile = path.join(__dirname, 'events', `${scenarioSlug}.json`);

  if (!fs.existsSync(eventFile)) {
    console.error(`Event file not found: ${eventFile}`);
    process.exit(1);
  }

  const eventData = JSON.parse(fs.readFileSync(eventFile, 'utf-8'));

  let success = false;

  try {
    logger.start();

    const requirementsReady = await ensureRequirements(logger);
    if (!requirementsReady) {
      throw new Error('Requirements not ready');
    }

    // Log inputs
    for (const input of eventData.inputs) {
      logger.input(input.name, input.value);
    }

    // Get the scenario runner
    const runner = scenarioRunners[scenarioSlug];
    if (!runner) {
      throw new Error(`No runner found for scenario: ${scenarioSlug}`);
    }

    // Execute the scenario runner
    logger.log('info', `Running scenario: ${scenarioSlug}`);
    const result = await runner(eventData.inputs, logger);

    // Log the overall result
    logger.output('scenario_result', result);

    // Verify assertions if expectedOutputs exist
    if (eventData.expectedOutputs && eventData.expectedOutputs.length > 0) {
      for (const expected of eventData.expectedOutputs) {
        // Extract the relevant value from result based on expected output name
        const actualValue = Object.prototype.hasOwnProperty.call(result, expected.name)
          ? result[expected.name]
          : result;

        const passed = checkAssertion(expected, actualValue);
        logger.assertion(expected.name, passed, expected.assertion, actualValue);

        if (!passed) {
          throw new Error(`Assertion failed: ${expected.name}`);
        }
      }
    }

    success = true;

  } catch (err) {
    logger.error('Execution failed', err);
    success = false;
  } finally {
    await cleanup(logger);
    logger.end(success, success ? null : 'See error events above');
  }

  process.exit(success ? 0 : 1);
}

main().catch((err) => {
  console.error('Fatal error:', err);
  process.exit(1);
});
